"use client";

import Image from "next/image";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";

import { Dashboard } from "@/features";

import { StoreProvider } from "./StoreProvider";

// import "./styles/globals.css";
import styles from "./styles/layout.module.css";

const darkTheme = createTheme({
    palette: {
        mode: "dark",
        background: {
            default: "#323232",
            paper: "#282828"
        }
    }, 

});

// export const metadata: Metadata = {
//     title: "Crypto Restake",
//     description: "Generated by create next app",
//   };

interface Props {
    readonly children: ReactNode;
}

export default function RootLayout({ children }: Props) {
    return (
        <StoreProvider>
            <html lang="en">
                <body>
                    <ThemeProvider theme={darkTheme}>
                        <CssBaseline />
                        <Dashboard>
                            <main className={styles.main}>{children}</main>
                        </Dashboard>
                    </ThemeProvider>
                </body>
            </html>
        </StoreProvider>
    );
}
